title: Finding substrings with Python
hero_image: images/banner.png
description: Find substrings in a string with Python
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
interests: ""
technologies: "python"
steps:
  - title: Find a substring

