title: generic-python-finding-substrings
hero_image: images/banner.png
subtitle: generic-python-finding-substrings subtitle
description: generic-python-finding-substrings description
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
published: false
steps:
  - title: Step one
    duration: 60
